import fs from "node:fs"; import zlib from "node:zlib";
const f = process.argv[2];
const raw = zlib.gunzipSync(fs.readFileSync(f)).toString("utf8");
let j = JSON.parse(raw);
const top = j.data ?? j;
console.log("top keys", Object.keys(top).slice(0,40));
const ps = typeof top.PlayerSave === "string" ? JSON.parse(top.PlayerSave) : top.PlayerSave;
const p = ps.data ?? ps;
console.log("player keys", Object.keys(p).join(","));
console.log("bitNodeN", p.bitNodeN, "SF", JSON.stringify(p.sourceFiles), "hack", p.skills, "exp", p.exp);
console.log("augs", p.augmentations.length, p.augmentations.map(a=>a.name+(a.level>1?":"+a.level:"")).join("|"));
console.log("queued", p.queuedAugmentations.map(a=>a.name).join("|"));
console.log("money", p.money, "playtime since aug", p.playtimeSinceLastAug, "since BN", p.playtimeSinceLastBitnode, "lastAug", p.lastAugReset, "lastNode", p.lastNodeReset);
console.log("mults", JSON.stringify(p.mults));
console.log("factions", p.factions.join("|"));
console.log("jobs", JSON.stringify(p.jobs));
console.log("hasWseAccount",p.hasWseAccount,"has4S",p.has4SData,p.has4SDataTixApi,"hasTix",p.hasTixApiAccess);
console.log("city", p.city, "karma", p.karma, "entropy", p.entropy, "sleeves", (p.sleeves||[]).length);
console.log("hacknet", (p.hacknetNodes||[]).length, "hashes", JSON.stringify(p.hashManager?.data?.hashes));
